version: "3.8"
services:
  erc20-swap:
    image: vmbc-eth-starter-kit/vmbc-erc20-swap:1.0
    container_name: vmbc-erc20-swap-kit
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - VMBC_URL=http://host.docker.internal:8545
      - VMBC_CHAIN_ID=5000
    ports:
      - 3000:3000
