apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-erc20-swap.yml -o k8s-erc20-swap.yml
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.service: erc20-swap
      name: erc20-swap
    spec:
      ports:
        - name: "3000"
          port: 3000
          targetPort: 3000
      selector:
        io.kompose.service: erc20-swap
    status:
      loadBalancer: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-erc20-swap.yml -o k8s-erc20-swap.yml
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.service: erc20-swap
      name: erc20-swap
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: erc20-swap
      strategy: {}
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -f docker-compose-erc20-swap.yml -o k8s-erc20-swap.yml
            kompose.version: 1.24.0 (4a2a0458)
          creationTimestamp: null
          labels:
            io.kompose.service: erc20-swap
        spec:
          containers:
            - env:
                - name: VMBC_CHAIN_ID
                  value: "5000"
                - name: VMBC_URL
                  value: http://host.docker.internal:8545
              image: vmbc-eth-starter-kit/vmbc-erc20-swap:1.0
              imagePullPolicy: Never
              name: vmbc-erc20-swap-kit
              ports:
                - containerPort: 3000
              resources: {}
          restartPolicy: Always
    status: {}
kind: List
metadata: {}

